// Game logic usiing javascript as we know 

// we define first input here. 
const input = document.getElementById("guess-input");

const submitBtn = document.getElementById("submit-btn");

const restartBtn = document.getElementById("restart-btn");

const message = document.getElementById("message");

const attemptsDisplay = document.getElementById("attempts-left"); // for changing what the its 
// the containt inside is we uised thes. 


let secretNumber; // random number is generated by computer which wew need to find out. 

let attemptsLeft = 10;

function startGame() {
    secretNumber = Math.floor(Math.random() * 51); // it is creating a generarnal random number understand that. 
    attemptsLeft = 10;
    attemptsDisplay.textContent = attemptsLeft;
    message.textContent = "";
    input.disabled = false;
    submitBtn.disabled = false;
    restartBtn.style.display = "none";
    input.value = "";
    input.focus();

}


function checkGuess() {
    const userInput = input.value.trim();

    if (userInput === ""
    ) {
        message.textContent = "Input cannot be empty , write somethings mf beep";
    }

    const guess = Number(userInput); // for chehcking the correctness of the number 
    if(isNaN(guess) || guess < 0 || guess > 50) {
        message.textContent = "Pagal  number 0 ra 50 ko bich ho kya"
    return; 
    }

attemptsLeft--; 
attemptsDisplay.textContent = attemptsLeft; 

let feedback = `You entered: ${guess}.`; 

if(guess === secretNumber){
    feedback += `Correct! you are right the number was ${secretNumber}`;
    endGame(); 
} else if(attemptsLeft === 0){
    feedback += `Game Over(Aloo Kais, Ja***a)! The number was ${secretNumber}.`; 
    message.textContent = feedback; 
    endGame(); 
}   else if(guess < secretNumber) {
    feedback += "Too Low, try again ran***i";
    message.textContent = feedback;  
} else {
    feedback += "Too high. try again m***i"; 
    message.textContent = feedback;
}


// for value increasing thhe input we use thhis. understand that. buddy. 
input.value = ""; 
input.focus(); 

}
function endGame() {
    input.disabled = true; 
    submitBtn.disabled = true; 
    restartBtn.style.display = "inline-block";

}

// for submit button addenvent leistner understand that 

submitBtn.addEventListener("click", checkGuess);
restartBtn.addEventListener("click", startGame);
input.addEventListener("keydown", (e) => {
    if(e.key === "Enter") checkGuess();
})


// by defualut we styart the game 
startGame(); 
